=== C-Kennelly/HaloSharp/Source/HaloSharp.Test/JSON/Stats/leaderboard.schema.json
{
  "definitions": {
    "Result": {
      "type": "object",
      "properties": {
        "Player": {
          "$ref": "common/identity.schema.json"
        },
        "Rank": {
          "type": "integer"
        },
        "Score": {
          "$ref": "common/competitive-skill-ranking.schema.json"
        }
      },
      "required": [
        "Player",
        "Rank",
        "Score"
      ],
      "additionalProperties": false
    }
  },

  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "Start": {
      "type": "integer"
    },
    "Count": {
      "type": "integer"
    },
    "ResultCount": {
      "type": "integer"
    },
    "Results": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Result"
      }
    },
    "Links": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Self": {
          "$ref": "common/link.schema.json"
        }
      },
      "required": [
        "Self"
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "Start",
    "Count",
    "ResultCount",
    "Results",
    "Links"
  ]
}

=== C-Kennelly/HaloSharp/Source/HaloSharp.Test/JSON/Halo5/Stats/leaderboard.json
{
    "Start":0,
    "Count":200,
    "ResultCount":200,
    "Results":[
        {
            "Player":{
                "Gamertag":"OpTic FORRMAL",
                "Xuid":null
            },
            "Rank":1,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2978,
                "PercentToNextTier":0,
                "Rank":1
            }
        },
        {
            "Player":{
                "Gamertag":"PTER0DACTYLSFTW",
                "Xuid":null
            },
            "Rank":2,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2622,
                "PercentToNextTier":0,
                "Rank":2
            }
        },
        {
            "Player":{
                "Gamertag":"Retro JM",
                "Xuid":null
            },
            "Rank":3,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2591,
                "PercentToNextTier":0,
                "Rank":3
            }
        },
        {
            "Player":{
                "Gamertag":"I Neo l",
                "Xuid":null
            },
            "Rank":4,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2571,
                "PercentToNextTier":0,
                "Rank":4
            }
        },
        {
            "Player":{
                "Gamertag":"Dat Win Doe",
                "Xuid":null
            },
            "Rank":5,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2551,
                "PercentToNextTier":0,
                "Rank":5
            }
        },
        {
            "Player":{
                "Gamertag":"ADVIL RAGES",
                "Xuid":null
            },
            "Rank":6,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2544,
                "PercentToNextTier":0,
                "Rank":6
            }
        },
        {
            "Player":{
                "Gamertag":"JR2 WORLDSTARS",
                "Xuid":null
            },
            "Rank":7,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2522,
                "PercentToNextTier":0,
                "Rank":7
            }
        },
        {
            "Player":{
                "Gamertag":"NinjaArtss",
                "Xuid":null
            },
            "Rank":8,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2521,
                "PercentToNextTier":0,
                "Rank":8
            }
        },
        {
            "Player":{
                "Gamertag":"Qristola",
                "Xuid":null
            },
            "Rank":9,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2513,
                "PercentToNextTier":0,
                "Rank":9
            }
        },
        {
            "Player":{
                "Gamertag":"Aries cAries",
                "Xuid":null
            },
            "Rank":10,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2505,
                "PercentToNextTier":0,
                "Rank":10
            }
        },
        {
            "Player":{
                "Gamertag":"Dylan is Insane",
                "Xuid":null
            },
            "Rank":11,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2499,
                "PercentToNextTier":0,
                "Rank":11
            }
        },
        {
            "Player":{
                "Gamertag":"Saiynts",
                "Xuid":null
            },
            "Rank":12,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2498,
                "PercentToNextTier":0,
                "Rank":12
            }
        },
        {
            "Player":{
                "Gamertag":"Cafee Con Leche",
                "Xuid":null
            },
            "Rank":13,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2497,
                "PercentToNextTier":0,
                "Rank":13
            }
        },
        {
            "Player":{
                "Gamertag":"RowaN da Boat",
                "Xuid":null
            },
            "Rank":14,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2489,
                "PercentToNextTier":0,
                "Rank":14
            }
        },
        {
            "Player":{
                "Gamertag":"Shotzzy tK",
                "Xuid":null
            },
            "Rank":15,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2478,
                "PercentToNextTier":0,
                "Rank":15
            }
        },
        {
            "Player":{
                "Gamertag":"JJuicyFruit",
                "Xuid":null
            },
            "Rank":16,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2475,
                "PercentToNextTier":0,
                "Rank":16
            }
        },
        {
            "Player":{
                "Gamertag":"Envsty",
                "Xuid":null
            },
            "Rank":17,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2466,
                "PercentToNextTier":0,
                "Rank":17
            }
        },
        {
            "Player":{
                "Gamertag":"Buh Bye Bruh",
                "Xuid":null
            },
            "Rank":18,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2464,
                "PercentToNextTier":0,
                "Rank":18
            }
        },
        {
            "Player":{
                "Gamertag":"Krehxy",
                "Xuid":null
            },
            "Rank":19,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2461,
                "PercentToNextTier":0,
                "Rank":19
            }
        },
        {
            "Player":{
                "Gamertag":"Musa eH",
                "Xuid":null
            },
            "Rank":20,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2460,
                "PercentToNextTier":0,
                "Rank":20
            }
        },
        {
            "Player":{
                "Gamertag":"Very Nerdy",
                "Xuid":null
            },
            "Rank":21,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2458,
                "PercentToNextTier":0,
                "Rank":21
            }
        },
        {
            "Player":{
                "Gamertag":"Dewbron",
                "Xuid":null
            },
            "Rank":22,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2456,
                "PercentToNextTier":0,
                "Rank":22
            }
        },
        {
            "Player":{
                "Gamertag":"ProThatNevrWas",
                "Xuid":null
            },
            "Rank":23,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2452,
                "PercentToNextTier":0,
                "Rank":23
            }
        },
        {
            "Player":{
                "Gamertag":"Lion XL",
                "Xuid":null
            },
            "Rank":23,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2452,
                "PercentToNextTier":0,
                "Rank":23
            }
        },
        {
            "Player":{
                "Gamertag":"bubu dubu",
                "Xuid":null
            },
            "Rank":25,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2447,
                "PercentToNextTier":0,
                "Rank":25
            }
        },
        {
            "Player":{
                "Gamertag":"Atzo Uchiha",
                "Xuid":null
            },
            "Rank":26,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2445,
                "PercentToNextTier":0,
                "Rank":26
            }
        },
        {
            "Player":{
                "Gamertag":"NYSea",
                "Xuid":null
            },
            "Rank":27,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2438,
                "PercentToNextTier":0,
                "Rank":27
            }
        },
        {
            "Player":{
                "Gamertag":"Sneaky Bran",
                "Xuid":null
            },
            "Rank":28,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2433,
                "PercentToNextTier":0,
                "Rank":28
            }
        },
        {
            "Player":{
                "Gamertag":"Fizzle Fox",
                "Xuid":null
            },
            "Rank":29,
            "Score":{
                "Tier":1,
                "DesignationId":7,
                "Csr":2431,
                "PercentToNextTier":0,
                "Rank":29
            }
        },
        {
            "Player":{
